//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace KMyMoney_Thesis
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<kmmAccounts>();
                db.CreateTable<kmmAccountsPayeeIdentifier>();
                db.CreateTable<kmmBudgetConfig>();
                db.CreateTable<kmmCostCenter>();
                db.CreateTable<kmmCurrencies>();
                db.CreateTable<kmmFileInfo>();
                db.CreateTable<kmmInstitutions>();
                db.CreateTable<kmmKeyValuePairs>();
                db.CreateTable<kmmOnlineJobs>();
                db.CreateTable<kmmPayeeIdentifier>();
                db.CreateTable<kmmPayees>();
                db.CreateTable<kmmPayeesPayeeIdentifier>();
                db.CreateTable<kmmPluginInfo>();
                db.CreateTable<kmmPrices>();
                db.CreateTable<kmmReportConfig>();
                db.CreateTable<kmmSchedulePaymentHistory>();
                db.CreateTable<kmmSchedules>();
                db.CreateTable<kmmSecurities>();
                db.CreateTable<kmmSplits>();
                db.CreateTable<kmmTags>();
                db.CreateTable<kmmTagSplits>();
                db.CreateTable<kmmTransactions>();
            }
        }
    }
    public partial class kmmAccounts
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [MaxLength(32)]
        public String institutionId { get; set; }
        
        [MaxLength(32)]
        public String parentId { get; set; }
        
        public DateTime? lastReconciled { get; set; }
        
        public DateTime? lastModified { get; set; }
        
        public DateTime? openingDate { get; set; }
        
        public Object accountNumber { get; set; }
        
        [MaxLength(16)]
        [NotNull]
        public String accountType { get; set; }
        
        public Object accountTypeString { get; set; }
        
        [MaxLength(1)]
        public String isStockAccount { get; set; }
        
        public Object accountName { get; set; }
        
        public Object description { get; set; }
        
        [MaxLength(32)]
        public String currencyId { get; set; }
        
        public Object balance { get; set; }
        
        public Object balanceFormatted { get; set; }
        
        public Object transactionCount { get; set; }
        
    }
    
    public partial class kmmAccountsPayeeIdentifier
    {
        [MaxLength(32)]
        [NotNull]
        public String accountId { get; set; }
        
        [NotNull]
        public Object userorder { get; set; }
        
        [MaxLength(32)]
        [NotNull]
        public String identifierId { get; set; }
        
    }
    
    public partial class kmmBudgetConfig
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [NotNull]
        public String name { get; set; }
        
        [NotNull]
        public DateTime start { get; set; }
        
        public String XML { get; set; }
        
    }
    
    public partial class kmmCostCenter
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [NotNull]
        public String name { get; set; }
        
    }
    
    public partial class kmmCurrencies
    {
        [PrimaryKey]
        [MaxLength(3)]
        public String ISOcode { get; set; }
        
        [NotNull]
        public String name { get; set; }
        
        public Object type { get; set; }
        
        public Object typeString { get; set; }
        
        public Object symbol1 { get; set; }
        
        public Object symbol2 { get; set; }
        
        public Object symbol3 { get; set; }
        
        [MaxLength(255)]
        public String symbolString { get; set; }
        
        [MaxLength(24)]
        public String partsPerUnit { get; set; }
        
        [MaxLength(24)]
        public String smallestCashFraction { get; set; }
        
        [MaxLength(24)]
        public String smallestAccountFraction { get; set; }
        
    }
    
    public partial class kmmFileInfo
    {
        [MaxLength(16)]
        public String version { get; set; }
        
        public DateTime? created { get; set; }
        
        public DateTime? lastModified { get; set; }
        
        [MaxLength(3)]
        public String baseCurrency { get; set; }
        
        public Object institutions { get; set; }
        
        public Object accounts { get; set; }
        
        public Object payees { get; set; }
        
        public Object tags { get; set; }
        
        public Object transactions { get; set; }
        
        public Object splits { get; set; }
        
        public Object securities { get; set; }
        
        public Object prices { get; set; }
        
        public Object currencies { get; set; }
        
        public Object schedules { get; set; }
        
        public Object reports { get; set; }
        
        public Object kvps { get; set; }
        
        public DateTime? dateRangeStart { get; set; }
        
        public DateTime? dateRangeEnd { get; set; }
        
        public Object hiInstitutionId { get; set; }
        
        public Object hiPayeeId { get; set; }
        
        public Object hiTagId { get; set; }
        
        public Object hiAccountId { get; set; }
        
        public Object hiTransactionId { get; set; }
        
        public Object hiScheduleId { get; set; }
        
        public Object hiSecurityId { get; set; }
        
        public Object hiReportId { get; set; }
        
        [MaxLength(255)]
        public String encryptData { get; set; }
        
        [MaxLength(1)]
        public String updateInProgress { get; set; }
        
        public Object budgets { get; set; }
        
        public Object hiBudgetId { get; set; }
        
        public Object hiOnlineJobId { get; set; }
        
        public Object hiPayeeIdentifierId { get; set; }
        
        [MaxLength(255)]
        public String logonUser { get; set; }
        
        public DateTime? logonAt { get; set; }
        
        public Object fixLevel { get; set; }
        
    }
    
    public partial class kmmInstitutions
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [NotNull]
        public String name { get; set; }
        
        public Object manager { get; set; }
        
        public Object routingCode { get; set; }
        
        public Object addressStreet { get; set; }
        
        public Object addressCity { get; set; }
        
        public Object addressZipcode { get; set; }
        
        public Object telephone { get; set; }
        
    }
    
    public partial class kmmKeyValuePairs
    {
        [Indexed(Name = "kmmKeyValuePairs_type_id_idx", Order = 0)]
        [MaxLength(16)]
        [NotNull]
        public String kvpType { get; set; }
        
        [Indexed(Name = "kmmKeyValuePairs_type_id_idx", Order = 1)]
        [MaxLength(32)]
        public String kvpId { get; set; }
        
        [MaxLength(255)]
        [NotNull]
        public String kvpKey { get; set; }
        
        public Object kvpData { get; set; }
        
    }
    
    public partial class kmmOnlineJobs
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [MaxLength(255)]
        [NotNull]
        public String type { get; set; }
        
        public DateTime? jobSend { get; set; }
        
        public DateTime? bankAnswerDate { get; set; }
        
        [MaxLength(15)]
        [NotNull]
        public String state { get; set; }
        
        [MaxLength(1)]
        [NotNull]
        public String locked { get; set; }
        
    }
    
    public partial class kmmPayeeIdentifier
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [MaxLength(255)]
        public String type { get; set; }
        
    }
    
    public partial class kmmPayees
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        public Object name { get; set; }
        
        public Object reference { get; set; }
        
        public Object email { get; set; }
        
        public Object addressStreet { get; set; }
        
        public Object addressCity { get; set; }
        
        public Object addressZipcode { get; set; }
        
        public Object addressState { get; set; }
        
        public Object telephone { get; set; }
        
        public String notes { get; set; }
        
        [MaxLength(32)]
        public String defaultAccountId { get; set; }
        
        public Object matchData { get; set; }
        
        [MaxLength(1)]
        public String matchIgnoreCase { get; set; }
        
        public Object matchKeys { get; set; }
        
    }
    
    public partial class kmmPayeesPayeeIdentifier
    {
        [MaxLength(32)]
        [NotNull]
        public String payeeId { get; set; }
        
        [NotNull]
        public Object userorder { get; set; }
        
        [MaxLength(32)]
        [NotNull]
        public String identifierId { get; set; }
        
    }
    
    public partial class kmmPluginInfo
    {
        [PrimaryKey]
        [MaxLength(255)]
        public String iid { get; set; }
        
        [NotNull]
        public Object versionMajor { get; set; }
        
        public Object versionMinor { get; set; }
        
        public String uninstallQuery { get; set; }
        
    }
    
    public partial class kmmPrices
    {
        [MaxLength(32)]
        [NotNull]
        public String fromId { get; set; }
        
        [MaxLength(32)]
        [NotNull]
        public String toId { get; set; }
        
        [NotNull]
        public DateTime priceDate { get; set; }
        
        [NotNull]
        public String price { get; set; }
        
        public Object priceFormatted { get; set; }
        
        public Object priceSource { get; set; }
        
    }
    
    public partial class kmmReportConfig
    {
        [MaxLength(255)]
        [NotNull]
        public String name { get; set; }
        
        public String XML { get; set; }
        
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
    }
    
    public partial class kmmSchedulePaymentHistory
    {
        [MaxLength(32)]
        [NotNull]
        public String schedId { get; set; }
        
        [NotNull]
        public DateTime payDate { get; set; }
        
    }
    
    public partial class kmmSchedules
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [NotNull]
        public String name { get; set; }
        
        [NotNull]
        public Object type { get; set; }
        
        public Object typeString { get; set; }
        
        [NotNull]
        public Object occurence { get; set; }
        
        [NotNull]
        public Object occurenceMultiplier { get; set; }
        
        public Object occurenceString { get; set; }
        
        public Object paymentType { get; set; }
        
        public String paymentTypeString { get; set; }
        
        [NotNull]
        public DateTime startDate { get; set; }
        
        public DateTime? endDate { get; set; }
        
        [MaxLength(1)]
        [NotNull]
        public String Fixed { get; set; }
        
        [MaxLength(1)]
        [NotNull]
        public String lastDayInMonth { get; set; }
        
        [MaxLength(1)]
        [NotNull]
        public String autoEnter { get; set; }
        
        public DateTime? lastPayment { get; set; }
        
        public DateTime? nextPaymentDue { get; set; }
        
        [NotNull]
        public Object weekendOption { get; set; }
        
        public Object weekendOptionString { get; set; }
        
    }
    
    public partial class kmmSecurities
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [NotNull]
        public String name { get; set; }
        
        public Object symbol { get; set; }
        
        [NotNull]
        public Object type { get; set; }
        
        public Object typeString { get; set; }
        
        [MaxLength(24)]
        public String smallestAccountFraction { get; set; }
        
        public Object tradingMarket { get; set; }
        
        [MaxLength(3)]
        public String tradingCurrency { get; set; }
        
    }
    
    public partial class kmmSplits
    {
        [MaxLength(32)]
        [NotNull]
        public String transactionId { get; set; }
        
        [Indexed(Name = "kmmSplits_kmmSplitsaccount_type_idx", Order = 1)]
        [MaxLength(1)]
        public String txType { get; set; }
        
        [NotNull]
        public Object splitId { get; set; }
        
        [MaxLength(32)]
        public String payeeId { get; set; }
        
        public DateTime? reconcileDate { get; set; }
        
        [MaxLength(16)]
        public String action { get; set; }
        
        [MaxLength(1)]
        public String reconcileFlag { get; set; }
        
        [NotNull]
        public String value { get; set; }
        
        public String valueFormatted { get; set; }
        
        [NotNull]
        public String shares { get; set; }
        
        public Object sharesFormatted { get; set; }
        
        public String price { get; set; }
        
        public Object priceFormatted { get; set; }
        
        public Object memo { get; set; }
        
        [Indexed(Name = "kmmSplits_kmmSplitsaccount_type_idx", Order = 0)]
        [MaxLength(32)]
        [NotNull]
        public String accountId { get; set; }
        
        [MaxLength(32)]
        public String costCenterId { get; set; }
        
        [MaxLength(32)]
        public String checkNumber { get; set; }
        
        public DateTime? postDate { get; set; }
        
        public Object bankId { get; set; }
        
    }
    
    public partial class kmmTags
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        public Object name { get; set; }
        
        [MaxLength(1)]
        public String closed { get; set; }
        
        public String notes { get; set; }
        
        public Object tagColor { get; set; }
        
    }
    
    public partial class kmmTagSplits
    {
        [MaxLength(32)]
        [NotNull]
        public String transactionId { get; set; }
        
        [MaxLength(32)]
        [NotNull]
        public String tagId { get; set; }
        
        [NotNull]
        public Object splitId { get; set; }
        
    }
    
    public partial class kmmTransactions
    {
        [PrimaryKey]
        [MaxLength(32)]
        public String id { get; set; }
        
        [MaxLength(1)]
        public String txType { get; set; }
        
        public DateTime? postDate { get; set; }
        
        public Object memo { get; set; }
        
        public DateTime? entryDate { get; set; }
        
        [MaxLength(3)]
        public String currencyId { get; set; }
        
        public Object bankId { get; set; }
        
    }
    
    public partial class kmmBalances
    {
        [MaxLength(32)]
        [NotNull]
        public String id { get; set; }
        
        [MaxLength(32)]
        public String currencyId { get; set; }
        
        [MaxLength(1)]
        public String txType { get; set; }
        
        [NotNull]
        public String value { get; set; }
        
        [NotNull]
        public String shares { get; set; }
        
        public DateTime? balDate { get; set; }
        
        [MaxLength(3)]
        public String txCurrencyId { get; set; }
        
    }
    
}
