//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System;
using System.Collections.Generic;
using Microcharts;
using SkiaSharp;
//using Entry = Microcharts.ChartEntry;
using Xamarin.Forms;

namespace KMyMoney_Thesis.Charts
{
    public partial class AssetsAndLiabilitiesChart : ContentPage
    {
        List<ChartEntry> entries = new List<ChartEntry>
        {
            new ChartEntry(200)
            {
                Color = SKColor.Parse("#FF1493"),
                Label = "Label1",
                ValueLabel = "200"
            },
            new ChartEntry(400)
            {
                Color = SKColor.Parse("#00BFFF"),
                Label = "Label2",
                ValueLabel = "400"
            }
        };
        public AssetsAndLiabilitiesChart()
        {
            InitializeComponent();

            Chart1.Chart = new RadialGaugeChart { Entries = entries };
        }
    }
}
